!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 14 Mar 2025 11:54
!
MODULE FORWARD_DIFF
  IMPLICIT NONE

CONTAINS
!  Differentiation of forward_problem in reverse (adjoint) mode (with options OpenMP):
!   gradient     of useful results: v
!   with respect to varying inputs: v xx
!   RW status of diff variables: v:in-zero xx:out
  SUBROUTINE FORWARD_PROBLEM_B(xx, xxb, v, vb)
    IMPLICIT NONE
    INTEGER :: i
    REAL*8, DIMENSION(10000), INTENT(IN) :: xx
    REAL*8, DIMENSION(10000) :: xxb
    REAL*8, DIMENSION(10000) :: vi
    REAL*8, DIMENSION(10000) :: vib
    REAL*8 :: v
    REAL*8 :: vb
    REAL*8 :: tap_temp_abs1, tap_temp_abs2, tap_temp_abs3, tap_temp_max1, tap_temp_max2
    REAL*8 :: tap_temp_abs1b, tap_temp_abs2b, tap_temp_abs3b, tap_temp_max1b, tap_temp_max2b
    INTRINSIC SIN
    INTRINSIC ABS
    INTRINSIC MAX
    INTRINSIC SUM
    INTEGER*4 :: branch
    INTEGER :: chunk_start
    INTEGER :: chunk_end
!$OMP PARALLEL DEFAULT(shared), PRIVATE(i, tap_temp_abs1, tap_temp_abs2, tap_temp_abs3, tap_temp_max1, tap_temp_max2), PRIVATE(chunk_start, chunk_end)
    CALL GETSTATICSCHEDULE(1, 10000, 1, chunk_start, chunk_end)
    DO i=chunk_start,chunk_end
      IF (xx(i)**2 + xx(i)**3 .GE. 0) THEN
! sin function
        vi(i) = SIN(xx(i))
        IF (xx(i) .GE. 0.) THEN
          tap_temp_abs1 = xx(i)
          CALL PUSHCONTROL1B(0)
        ELSE
          tap_temp_abs1 = -xx(i)
          CALL PUSHCONTROL1B(1)
        END IF
        vi(i) = vi(i) + tap_temp_abs1
        IF (xx(i) .LT. 1.0) THEN
          CALL PUSHCONTROL1B(0)
          tap_temp_max1 = 1.0
        ELSE
          tap_temp_max1 = xx(i)
          CALL PUSHCONTROL1B(1)
        END IF
        vi(i) = vi(i) + tap_temp_max1
        IF (xx(i) .GE. 0.) THEN
          CALL PUSHREAL8(tap_temp_abs2)
          tap_temp_abs2 = xx(i)
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHREAL8(tap_temp_abs2)
          tap_temp_abs2 = -xx(i)
          CALL PUSHCONTROL1B(1)
        END IF
        IF (xx(i) .GE. 0.) THEN
          tap_temp_abs3 = xx(i)
          CALL PUSHCONTROL1B(0)
        ELSE
          tap_temp_abs3 = -xx(i)
          CALL PUSHCONTROL1B(1)
        END IF
        IF (tap_temp_abs3 .LT. 1.0) THEN
          CALL PUSHREAL8(tap_temp_max2)
          tap_temp_max2 = 1.0
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHREAL8(tap_temp_max2)
          tap_temp_max2 = tap_temp_abs3
          CALL PUSHCONTROL1B(1)
        END IF
        vi(i) = vi(i) + tap_temp_abs2/tap_temp_max2
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
    END DO
    CALL PUSHREAL8(tap_temp_abs2)
    CALL PUSHREAL8(tap_temp_max2)
!$OMP END PARALLEL
    vib = 0.0_8
    vib = vb
    xxb = 0.0_8
!$OMP PARALLEL DEFAULT(shared), PRIVATE(i, tap_temp_abs1, tap_temp_abs2, tap_temp_abs3, tap_temp_max1, tap_temp_max2), PRIVATE(tap_temp_abs1b, tap_temp_abs2b, tap_temp_abs3b, tap_temp_max1b, tap_temp_max2b), PRIVATE(branch, chunk_end, chunk_start)
    CALL POPREAL8(tap_temp_max2)
    CALL POPREAL8(tap_temp_abs2)
    tap_temp_abs1b = 0.0_8
    tap_temp_abs2b = 0.0_8
    tap_temp_abs3b = 0.0_8
    tap_temp_max1b = 0.0_8
    tap_temp_max2b = 0.0_8
!    xxb = 0.0_8
    CALL GETSTATICSCHEDULE(1, 10000, 1, chunk_start, chunk_end)
    DO i=chunk_end,chunk_start,-1
      CALL POPCONTROL1B(branch)
      IF (branch .NE. 0) THEN
        tap_temp_abs2b = vib(i)/tap_temp_max2
        tap_temp_max2b = -(tap_temp_abs2*vib(i)/tap_temp_max2**2)
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          CALL POPREAL8(tap_temp_max2)
          tap_temp_abs3b = 0.0_8
        ELSE
          CALL POPREAL8(tap_temp_max2)
          tap_temp_abs3b = tap_temp_max2b
        END IF
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          xxb(i) = xxb(i) + tap_temp_abs3b
        ELSE
          xxb(i) = xxb(i) - tap_temp_abs3b
        END IF
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          CALL POPREAL8(tap_temp_abs2)
          xxb(i) = xxb(i) + tap_temp_abs2b
        ELSE
          CALL POPREAL8(tap_temp_abs2)
          xxb(i) = xxb(i) - tap_temp_abs2b
        END IF
        tap_temp_max1b = vib(i)
        CALL POPCONTROL1B(branch)
        IF (branch .NE. 0) xxb(i) = xxb(i) + tap_temp_max1b
        tap_temp_abs1b = vib(i)
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          xxb(i) = xxb(i) + tap_temp_abs1b
        ELSE
          xxb(i) = xxb(i) - tap_temp_abs1b
        END IF
        xxb(i) = xxb(i) + COS(xx(i))*vib(i)
        vib(i) = 0.0_8
      END IF
    END DO
!$OMP END PARALLEL
    vb = 0.0_8
  END SUBROUTINE FORWARD_PROBLEM_B

  SUBROUTINE FORWARD_PROBLEM(xx, v)
    IMPLICIT NONE
    INTEGER :: i
    REAL*8, DIMENSION(10000), INTENT(IN) :: xx
    REAL*8, DIMENSION(10000) :: vi
    REAL*8, INTENT(OUT) :: v
    REAL*8 :: tap_temp_abs1, tap_temp_abs2, tap_temp_abs3, tap_temp_max1, tap_temp_max2
    INTRINSIC SIN
    INTRINSIC ABS
    INTRINSIC MAX
    INTRINSIC SUM
!$OMP PARALLEL DO DEFAULT(shared), PRIVATE(i, tap_temp_abs1, tap_temp_abs2, tap_temp_abs3, tap_temp_max1, tap_temp_max2), SCHEDULE(static)
    DO i=1,10000
      IF (xx(i)**2 + xx(i)**3 .GE. 0) THEN
! sin function
        vi(i) = SIN(xx(i))
        IF (xx(i) .GE. 0.) THEN
          tap_temp_abs1 = xx(i)
        ELSE
          tap_temp_abs1 = -xx(i)
        END IF
        vi(i) = vi(i) + tap_temp_abs1
        IF (xx(i) .LT. 1.0) THEN
          tap_temp_max1 = 1.0
        ELSE
          tap_temp_max1 = xx(i)
        END IF
        vi(i) = vi(i) + tap_temp_max1
        IF (xx(i) .GE. 0.) THEN
          tap_temp_abs2 = xx(i)
        ELSE
          tap_temp_abs2 = -xx(i)
        END IF
        IF (xx(i) .GE. 0.) THEN
          tap_temp_abs3 = xx(i)
        ELSE
          tap_temp_abs3 = -xx(i)
        END IF
        IF (tap_temp_abs3 .LT. 1.0) THEN
          tap_temp_max2 = 1.0
        ELSE
          tap_temp_max2 = tap_temp_abs3
        END IF
        vi(i) = vi(i) + tap_temp_abs2/tap_temp_max2
      END IF
    END DO
    v = SUM(vi)
  END SUBROUTINE FORWARD_PROBLEM

END MODULE FORWARD_DIFF

