!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 14 Mar 2025 11:54
!
MODULE FORWARD_DIFF
  IMPLICIT NONE

CONTAINS
!  Differentiation of forward_problem in reverse (adjoint) mode (with options OpenMP):
!   gradient     of useful results: v
!   with respect to varying inputs: v xx
!   RW status of diff variables: v:in-zero xx:out
  SUBROUTINE FORWARD_PROBLEM_B(xx, xxb, v, vb)
    IMPLICIT NONE
    INTEGER :: i
    REAL*8, DIMENSION(10000), INTENT(IN) :: xx
    REAL*8, DIMENSION(10000) :: xxb
    REAL*8, DIMENSION(10000) :: vi
    REAL*8, DIMENSION(10000) :: vib
    REAL*8 :: v
    REAL*8 :: vb
    INTRINSIC SIN
    INTRINSIC ABS
    INTRINSIC MAX
    INTRINSIC SUM
    REAL*8 :: abs0
    REAL*8 :: abs0b
    REAL*8 :: max1
    REAL*8 :: max1b
    INTEGER*4 :: branch
    INTEGER :: chunk_start
    INTEGER :: chunk_end
!$OMP PARALLEL DEFAULT(shared), PRIVATE(i), PRIVATE(abs0, max1, chunk_start, chunk_end)
    CALL GETSTATICSCHEDULE(1, 10000, 1, chunk_start, chunk_end)
    DO i=chunk_start,chunk_end
      IF (xx(i)**2 + xx(i)**3 .GE. 0) THEN
! sin function
        vi(i) = SIN(xx(i))
        IF (xx(i) .GE. 0.) THEN
          abs0 = xx(i)
          CALL PUSHCONTROL1B(0)
        ELSE
          abs0 = -xx(i)
          CALL PUSHCONTROL1B(1)
        END IF
! abs function
        vi(i) = vi(i) + abs0
        IF (xx(i) .LT. 1.0) THEN
          CALL PUSHCONTROL1B(0)
          max1 = 1.0
        ELSE
          max1 = xx(i)
          CALL PUSHCONTROL1B(1)
        END IF
! max function
        vi(i) = vi(i) + max1
!! abs and max together
!vi(i) = vi(i) + abs(xx(i))/max(abs(xx(i)), 1.0)
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
    END DO
!$OMP END PARALLEL
    vib = 0.0_8
    vib = vb
    xxb = 0.0_8
!$OMP PARALLEL DEFAULT(shared), PRIVATE(i), PRIVATE(abs0, max1, branch, chunk_end, chunk_start), PRIVATE(abs0b, max1b)
!    xxb = 0.0_8
    CALL GETSTATICSCHEDULE(1, 10000, 1, chunk_start, chunk_end)
    DO i=chunk_end,chunk_start,-1
      CALL POPCONTROL1B(branch)
      IF (branch .NE. 0) THEN
        max1b = vib(i)
        CALL POPCONTROL1B(branch)
        IF (branch .NE. 0) xxb(i) = xxb(i) + max1b
        abs0b = vib(i)
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          xxb(i) = xxb(i) + abs0b
        ELSE
          xxb(i) = xxb(i) - abs0b
        END IF
        xxb(i) = xxb(i) + COS(xx(i))*vib(i)
        vib(i) = 0.0_8
      END IF
    END DO
!$OMP END PARALLEL
    vb = 0.0_8
  END SUBROUTINE FORWARD_PROBLEM_B

  SUBROUTINE FORWARD_PROBLEM(xx, v)
    IMPLICIT NONE
    INTEGER :: i
    REAL*8, DIMENSION(10000), INTENT(IN) :: xx
    REAL*8, DIMENSION(10000) :: vi
    REAL*8, INTENT(OUT) :: v
    INTRINSIC SIN
    INTRINSIC ABS
    INTRINSIC MAX
    INTRINSIC SUM
    REAL*8 :: abs0
    REAL*8 :: max1
!$OMP PARALLEL DO DEFAULT(shared), PRIVATE(i), PRIVATE(abs0, max1), SCHEDULE(static)
    DO i=1,10000
      IF (xx(i)**2 + xx(i)**3 .GE. 0) THEN
! sin function
        vi(i) = SIN(xx(i))
        IF (xx(i) .GE. 0.) THEN
          abs0 = xx(i)
        ELSE
          abs0 = -xx(i)
        END IF
! abs function
        vi(i) = vi(i) + abs0
        IF (xx(i) .LT. 1.0) THEN
          max1 = 1.0
        ELSE
          max1 = xx(i)
        END IF
! max function
        vi(i) = vi(i) + max1
!! abs and max together
!vi(i) = vi(i) + abs(xx(i))/max(abs(xx(i)), 1.0)
      END IF
    END DO
    v = SUM(vi)
  END SUBROUTINE FORWARD_PROBLEM

END MODULE FORWARD_DIFF

