!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 14 Mar 2025 11:54
!
MODULE FORWARD_TGT
  IMPLICIT NONE

CONTAINS
!  Differentiation of forward_problem in forward (tangent) mode (with options OpenMP):
!   variations   of useful results: v
!   with respect to varying inputs: xx
!   RW status of diff variables: v:out xx:in
  SUBROUTINE FORWARD_PROBLEM_D(xx, xxd, v, vd)
    IMPLICIT NONE
    INTEGER :: i
    REAL*8, DIMENSION(10), INTENT(IN) :: xx
    REAL*8, DIMENSION(10), INTENT(IN) :: xxd
    REAL*8, DIMENSION(10) :: vi
    REAL*8, DIMENSION(10) :: vid
    REAL*8 :: temp
    REAL*8 :: tempd
    REAL*8, INTENT(OUT) :: v
    REAL*8, INTENT(OUT) :: vd
    INTRINSIC SUM
    REAL*8 :: result1
    REAL*8 :: result1d
    vid = 0.0_8
!$OMP PARALLEL DO DEFAULT(shared), PRIVATE(i, temp), PRIVATE(tempd), PRIVATE(result1, result1d), SCHEDULE(static)
    DO i=1,10
      IF (xx(i)**2 + xx(i)**3 .GE. 0) THEN
! Inline function call
        result1d = DUMMY_FUNC_D(xx(i), xxd(i), result1)
        vid(i) = result1*xxd(i) + xx(i)*result1d
        vi(i) = 1.0 + xx(i)*result1
! Not inline function call
        tempd = DUMMY_FUNC_D(xx(i), xxd(i), temp)
        vid(i) = vid(i) + temp*xxd(i) + xx(i)*tempd
        vi(i) = vi(i) + 1.0 + xx(i)*temp
      END IF
    END DO
    vd = SUM(vid)
    v = SUM(vi)
  END SUBROUTINE FORWARD_PROBLEM_D

  SUBROUTINE FORWARD_PROBLEM(xx, v)
    IMPLICIT NONE
    INTEGER :: i
    REAL*8, DIMENSION(10), INTENT(IN) :: xx
    REAL*8, DIMENSION(10) :: vi
    REAL*8 :: temp
    REAL*8, INTENT(OUT) :: v
    INTRINSIC SUM
    REAL*8 :: result1
!$OMP PARALLEL DO DEFAULT(shared), PRIVATE(i, temp, result1), SCHEDULE(static)
    DO i=1,10
      IF (xx(i)**2 + xx(i)**3 .GE. 0) THEN
! Inline function call
        result1 = DUMMY_FUNC(xx(i))
        vi(i) = 1.0 + xx(i)*result1
! Not inline function call
        temp = DUMMY_FUNC(xx(i))
        vi(i) = vi(i) + 1.0 + xx(i)*temp
      END IF
    END DO
    v = SUM(vi)
  END SUBROUTINE FORWARD_PROBLEM

!  Differentiation of dummy_func in forward (tangent) mode (with options OpenMP):
!   variations   of useful results: dummy_func
!   with respect to varying inputs: x
  REAL*8 FUNCTION DUMMY_FUNC_D(x, xd, dummy_func)
    IMPLICIT NONE
    REAL*8 :: dummy_func
    REAL*8, INTENT(IN) :: x
    REAL*8, INTENT(IN) :: xd
    dummy_func_d = xd
    dummy_func = x + 1.0
  END FUNCTION DUMMY_FUNC_D

  FUNCTION DUMMY_FUNC(x)
    IMPLICIT NONE
    REAL*8 :: dummy_func
    REAL*8, INTENT(IN) :: x
    dummy_func = x + 1.0
  END FUNCTION DUMMY_FUNC

END MODULE FORWARD_TGT

