!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 14 Mar 2025 11:54
!
MODULE FORWARD_TGT
  IMPLICIT NONE

CONTAINS
!  Differentiation of forward_problem in forward (tangent) mode (with options OpenMP):
!   variations   of useful results: v
!   with respect to varying inputs: xx
!   RW status of diff variables: v:out xx:in
  SUBROUTINE FORWARD_PROBLEM_D(xx, xxd, v, vd)
    IMPLICIT NONE
    INTEGER :: i
    REAL*8, DIMENSION(10), INTENT(IN) :: xx
    REAL*8, DIMENSION(10), INTENT(IN) :: xxd
    REAL*8, DIMENSION(10) :: vi
    REAL*8, DIMENSION(10) :: vid
    REAL*8, INTENT(OUT) :: v
    REAL*8, INTENT(OUT) :: vd
    INTRINSIC SIN
    INTRINSIC ABS
    INTRINSIC MAX
    INTRINSIC SUM
    REAL*8 :: x1
    REAL*8 :: x1d
    REAL*8 :: abs0
    REAL*8 :: abs0d
    REAL*8 :: max1
    REAL*8 :: max1d
    REAL*8 :: abs1
    REAL*8 :: abs1d
    REAL*8 :: max2
    REAL*8 :: max2d
    vid = 0.0_8
!$OMP PARALLEL DO DEFAULT(shared), PRIVATE(i), PRIVATE(abs0, max1, abs1, max2), SCHEDULE(static)
    DO i=1,10
      IF (xx(i)**2 + xx(i)**3 .GE. 0) THEN
! sin function
        vid(i) = COS(xx(i))*xxd(i)
        vi(i) = SIN(xx(i))
        IF (xx(i) .GE. 0.) THEN
          abs0d = xxd(i)
          abs0 = xx(i)
        ELSE
          abs0d = -xxd(i)
          abs0 = -xx(i)
        END IF
! abs function
        vid(i) = vid(i) + abs0d
        vi(i) = vi(i) + abs0
        IF (xx(i) .LT. 1.0) THEN
          max1 = 1.0
          max1d = 0.0_8
        ELSE
          max1d = xxd(i)
          max1 = xx(i)
        END IF
! max function
        vid(i) = vid(i) + max1d
        vi(i) = vi(i) + max1
        IF (xx(i) .GE. 0.) THEN
          abs1d = xxd(i)
          abs1 = xx(i)
        ELSE
          abs1d = -xxd(i)
          abs1 = -xx(i)
        END IF
        IF (xx(i) .GE. 0.) THEN
          x1d = xxd(i)
          x1 = xx(i)
        ELSE
          x1d = -xxd(i)
          x1 = -xx(i)
        END IF
        IF (x1 .LT. 1.0) THEN
          max2 = 1.0
          max2d = 0.0_8
        ELSE
          max2d = x1d
          max2 = x1
        END IF
! abs and max together
        vid(i) = vid(i) + (abs1d-abs1*max2d/max2)/max2
        vi(i) = vi(i) + abs1/max2
      END IF
    END DO
    vd = SUM(vid)
    v = SUM(vi)
  END SUBROUTINE FORWARD_PROBLEM_D

  SUBROUTINE FORWARD_PROBLEM(xx, v)
    IMPLICIT NONE
    INTEGER :: i
    REAL*8, DIMENSION(10), INTENT(IN) :: xx
    REAL*8, DIMENSION(10) :: vi
    REAL*8, INTENT(OUT) :: v
    INTRINSIC SIN
    INTRINSIC ABS
    INTRINSIC MAX
    INTRINSIC SUM
    REAL*8 :: x1
    REAL*8 :: abs0
    REAL*8 :: max1
    REAL*8 :: abs1
    REAL*8 :: max2
!$OMP PARALLEL DO DEFAULT(shared), PRIVATE(i), SCHEDULE(static)
    DO i=1,10
      IF (xx(i)**2 + xx(i)**3 .GE. 0) THEN
! sin function
        vi(i) = SIN(xx(i))
        IF (xx(i) .GE. 0.) THEN
          abs0 = xx(i)
        ELSE
          abs0 = -xx(i)
        END IF
! abs function
        vi(i) = vi(i) + abs0
        IF (xx(i) .LT. 1.0) THEN
          max1 = 1.0
        ELSE
          max1 = xx(i)
        END IF
! max function
        vi(i) = vi(i) + max1
        IF (xx(i) .GE. 0.) THEN
          abs1 = xx(i)
        ELSE
          abs1 = -xx(i)
        END IF
        IF (xx(i) .GE. 0.) THEN
          x1 = xx(i)
        ELSE
          x1 = -xx(i)
        END IF
        IF (x1 .LT. 1.0) THEN
          max2 = 1.0
        ELSE
          max2 = x1
        END IF
! abs and max together
        vi(i) = vi(i) + abs1/max2
      END IF
    END DO
    v = SUM(vi)
  END SUBROUTINE FORWARD_PROBLEM

END MODULE FORWARD_TGT

