!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 14 Mar 2025 11:54
!
MODULE FORWARD_TGT
  IMPLICIT NONE

CONTAINS
!  Differentiation of forward_problem in forward (tangent) mode (with options OpenMP):
!   variations   of useful results: v
!   with respect to varying inputs: xx
!   RW status of diff variables: v:out xx:in
  SUBROUTINE FORWARD_PROBLEM_D(xx, xxd, v, vd)
    IMPLICIT NONE
    INTEGER :: i
    REAL*8, DIMENSION(10), INTENT(IN) :: xx
    REAL*8, DIMENSION(10), INTENT(IN) :: xxd
    REAL*8, DIMENSION(10) :: vi
    REAL*8, DIMENSION(10) :: vid
    REAL*8, INTENT(OUT) :: v
    REAL*8, INTENT(OUT) :: vd
    INTRINSIC SUM
    vid = 0.0_8
!$OMP PARALLEL DO DEFAULT(shared), PRIVATE(i), SCHEDULE(static)
    DO i=1,10
      vid(i) = xxd(i)
      vi(i) = xx(i) + 1.0
    END DO
    vd = SUM(vid)
    v = SUM(vi)
  END SUBROUTINE FORWARD_PROBLEM_D

  SUBROUTINE FORWARD_PROBLEM(xx, v)
    IMPLICIT NONE
    INTEGER :: i
    REAL*8, DIMENSION(10), INTENT(IN) :: xx
    REAL*8, DIMENSION(10) :: vi
    REAL*8, INTENT(OUT) :: v
    INTRINSIC SUM
!$OMP PARALLEL DO DEFAULT(shared), PRIVATE(i), SCHEDULE(static)
    DO i=1,10
      vi(i) = xx(i) + 1.0
    END DO
    v = SUM(vi)
  END SUBROUTINE FORWARD_PROBLEM

END MODULE FORWARD_TGT

