!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 14 Mar 2025 11:54
!
MODULE FORWARD_DIFF
  IMPLICIT NONE

CONTAINS
!  Differentiation of forward_problem in reverse (adjoint) mode (with options OpenMP):
!   gradient     of useful results: v
!   with respect to varying inputs: v xx
!   RW status of diff variables: v:in-zero xx:out
  SUBROUTINE FORWARD_PROBLEM_B(xx, xxb, v, vb)
    IMPLICIT NONE
    INTEGER :: i
    REAL*8, DIMENSION(10000), INTENT(IN) :: xx
    REAL*8, DIMENSION(10000) :: xxb
    REAL*8, DIMENSION(10000) :: vi
    REAL*8, DIMENSION(10000) :: vib
    REAL*8 :: v
    REAL*8 :: vb
    INTRINSIC ABS
    INTRINSIC MAX
    INTRINSIC SUM
    REAL*8 :: x1
    REAL*8 :: x1b
    REAL*8 :: abs0
    REAL*8 :: abs0b
    REAL*8 :: max1
    REAL*8 :: max1b
    INTEGER*4 :: branch
    INTEGER :: chunk_start
    INTEGER :: chunk_end
!$OMP PARALLEL DEFAULT(shared), PRIVATE(i), PRIVATE(abs0, max1, chunk_start, chunk_end)
    CALL GETSTATICSCHEDULE(1, 10000, 1, chunk_start, chunk_end)
    DO i=chunk_start,chunk_end
      IF (xx(i)**2 + xx(i)**3 .GE. 0) THEN
        IF (xx(i) .GE. 0.) THEN
          CALL PUSHREAL8(abs0)
          abs0 = xx(i)
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHREAL8(abs0)
          abs0 = -xx(i)
          CALL PUSHCONTROL1B(1)
        END IF
        IF (xx(i) .GE. 0.) THEN
          x1 = xx(i)
          CALL PUSHCONTROL1B(0)
        ELSE
          x1 = -xx(i)
          CALL PUSHCONTROL1B(1)
        END IF
        IF (x1 .LT. 1.0) THEN
          CALL PUSHREAL8(max1)
          max1 = 1.0
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHREAL8(max1)
          max1 = x1
          CALL PUSHCONTROL1B(1)
        END IF
!! sin function
!vi(i) = sin(xx(i))
!! abs function
!vi(i) = vi(i) + abs(xx(i))
!! max function
!vi(i) = vi(i) + max(xx(i), 1.0)
!! abs and max together
        vi(i) = vi(i) + abs0/max1
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
    END DO
    CALL PUSHREAL8(abs0)
    CALL PUSHREAL8(max1)
!$OMP END PARALLEL
    vib = 0.0_8
    vib = vb
    xxb = 0.0_8
!$OMP PARALLEL DEFAULT(shared), PRIVATE(i), PRIVATE(abs0, max1, branch, chunk_end, chunk_start)
    CALL POPREAL8(max1)
    CALL POPREAL8(abs0)
    xxb = 0.0_8
    CALL GETSTATICSCHEDULE(1, 10000, 1, chunk_start, chunk_end)
    DO i=chunk_end,chunk_start,-1
      CALL POPCONTROL1B(branch)
      IF (branch .NE. 0) THEN
        abs0b = vib(i)/max1
        max1b = -(abs0*vib(i)/max1**2)
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          CALL POPREAL8(max1)
          x1b = 0.0_8
        ELSE
          CALL POPREAL8(max1)
          x1b = max1b
        END IF
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          xxb(i) = xxb(i) + x1b
        ELSE
          xxb(i) = xxb(i) - x1b
        END IF
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          CALL POPREAL8(abs0)
          xxb(i) = xxb(i) + abs0b
        ELSE
          CALL POPREAL8(abs0)
          xxb(i) = xxb(i) - abs0b
        END IF
      END IF
    END DO
!$OMP END PARALLEL
    vb = 0.0_8
  END SUBROUTINE FORWARD_PROBLEM_B

  SUBROUTINE FORWARD_PROBLEM(xx, v)
    IMPLICIT NONE
    INTEGER :: i
    REAL*8, DIMENSION(10000), INTENT(IN) :: xx
    REAL*8, DIMENSION(10000) :: vi
    REAL*8, INTENT(OUT) :: v
    INTRINSIC ABS
    INTRINSIC MAX
    INTRINSIC SUM
    REAL*8 :: x1
    REAL*8 :: abs0
    REAL*8 :: max1
!$OMP PARALLEL DO DEFAULT(shared), PRIVATE(i), SCHEDULE(static)
    DO i=1,10000
      IF (xx(i)**2 + xx(i)**3 .GE. 0) THEN
        IF (xx(i) .GE. 0.) THEN
          abs0 = xx(i)
        ELSE
          abs0 = -xx(i)
        END IF
        IF (xx(i) .GE. 0.) THEN
          x1 = xx(i)
        ELSE
          x1 = -xx(i)
        END IF
        IF (x1 .LT. 1.0) THEN
          max1 = 1.0
        ELSE
          max1 = x1
        END IF
!! sin function
!vi(i) = sin(xx(i))
!! abs function
!vi(i) = vi(i) + abs(xx(i))
!! max function
!vi(i) = vi(i) + max(xx(i), 1.0)
!! abs and max together
        vi(i) = vi(i) + abs0/max1
      END IF
    END DO
    v = SUM(vi)
  END SUBROUTINE FORWARD_PROBLEM

END MODULE FORWARD_DIFF

